# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GTComonentDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GTComonentDemo
pod 'Kingfisher', '~> 5.15.7'
pod 'SnapKit', '~> 5.0.1'

pod "HomeComponent", :path =>"Component/HomeComponent/HomeComponent.podspec"
pod "UserCenterComponent", :path =>"Component/UserCenterComponent/UserCenterComponent.podspec"


# 做一些安装之后的hook
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) APPSTORE_CHANNEL=$(APPSTORE_CHANNEL)'
            config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D APPSTORE_CHANNEL'
            config.build_settings['GLOBAL'] = 1
        end
    end
end

end
#if config.name == 'Release'
#  config.build_settings['APPSTORE_CHANNEL'] = '1'
#end
